### ISSUE TITLE
Todos: Update set types

### ISSUE THREAD

**Issue by sthzg** [sthzg/django-filersets#118]
- [x]  On add settype -> ADD root category and SET relation
- [x]  On delete settype -> DELETE associated category tree
- [x]  On move root category -> Validate that move target remains on root level*
- [x]  On move child category -> Validate that move target remains on child level*
- [x]  On add category -> Validate addition to an allowed level *
- [x]  On delete root category -> Check if settype is connected and delete as well *
- [x]  On node move -> Ensure uniqueness of category slug.
- [x]  Refactor namespace to use the value from the slug field instead.. #120 
- [x]  Add created and updated timestamp to settype model. #119  
- [x]  Add created and updated timestamp to category model.
- [x]  Enhance admin set pages w/ Javascript to filter categories for set types. #111 
- [x]  Auto assign set to set type category on save.
- [x]  Ensure that on saving of set only categories belonging to set type can be saved.

\* The chances to do so should be circumvented by making this impossible on the UI. But even then it is a benefit to have an underlying validation layer to ensure these requirements.

**Comment by sthzg** [comment]
Related commit: 4f19aa6b2d236d61b4d900fdede5223a72f4cbfe
